import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { BrowserContext, Worker, Page } from 'playwright';
import { DEFAULT_RULES } from '../src/core';
import { SAMPLES } from '../src/samples';

export async function checkExtension(context: BrowserContext, worker: Worker, id: string, root: string, checks: string[]) {
  const files = await readdir(resolve(root, 'dist'));
  assert.ok(!files.includes('lab.html') && !files.includes('ui.js'));
  const manifest = JSON.parse(await readFile(resolve(root, 'dist/manifest.json'), 'utf8'));
  assert.equal(manifest.options_page, 'settings.html');
  const bundle = await readFile(resolve(root, 'dist/extension.js'), 'utf8');
  for (const marker of ['Open feed lab', 'Synthetic posts', 'Cedar AI', 'lab.html', '127.0.0.1']) assert.ok(!bundle.includes(marker), marker);
  checks.push('Production package contains controls and settings only; no lab or synthetic post data');
  let localRequests = 0;
  await context.route('http://127.0.0.1/**', route => { localRequests++; return route.abort(); });
  const popup = await context.newPage(); await popup.setViewportSize({ width: 360, height: 600 });
  await popup.goto(`chrome-extension://${id}/popup.html`);
  await popup.waitForFunction(() => document.getElementById('connection')?.textContent === 'Add API key');
  assert.equal(await popup.locator('#posts, #analyze, #post-text, #open-lab').count(), 0);
  await popup.locator('#api-key').fill('fixture-key-not-secret'); await popup.locator('#key-form button').click();
  await popup.waitForFunction(() => document.getElementById('connection')?.textContent === 'Connected');
  await popup.locator('#settings').evaluate((e: HTMLDetailsElement) => e.open = false);
  await popup.locator('#rules').fill(DEFAULT_RULES); await popup.locator('#apply-rules').click();
  await popup.waitForFunction(() => document.getElementById('rules-status')?.textContent === 'Applied');
  assert.ok((await popup.locator('#rules-feedback').innerText()).startsWith('Rules saved.'));
  await popup.screenshot({ path: resolve(root, 'artifacts/extension-popup-empty.png'), fullPage: true, animations: 'disabled' });
  checks.push('Popup saves BYOK and rules without a local server or test feed');

  await context.route('https://x.com/**', route => route.fulfill({ contentType: 'text/html', body: '<!doctype html><html><head><title>X-shaped test fixture</title><style>body{margin:30px auto;max-width:650px;font:16px Arial}article{border-bottom:1px solid #ddd;padding:14px}p{margin:8px}</style></head><body><main id="feed"></main></body></html>' }));
  const feed = await context.newPage(); await feed.setViewportSize({ width: 900, height: 1600 }); await feed.goto('https://x.com/home');
  await feed.evaluate(samples => {
    for (const post of samples) {
      const article = document.createElement('article'); article.dataset.testid = 'tweet'; article.id = post.id;
      const body = document.createElement('div'); const p = document.createElement('p'); p.dataset.testid = 'tweetText'; p.textContent = post.text;
      body.append(p); article.append(body); document.getElementById('feed')!.append(article);
    }
  }, SAMPLES);
  await feed.waitForFunction(() => [...document.querySelectorAll('feed-analysis-controls')].filter(e => e.shadowRoot?.textContent?.includes('Turn down')).length === 6);
  assert.equal(await feed.locator('article[data-fa-collapsed=true]').count(), 2);
  await popup.locator('#refresh-feed').click();
  await popup.waitForFunction(() => document.getElementById('feed-state')?.textContent?.startsWith('6 of 6'));
  checks.push('Packaged content script analyzes the X-shaped feed and popup reads its actual counts');
  await feed.locator('#sample-2').getByRole('button', { name: 'Show anyway' }).click();
  assert.equal(await feed.locator('#sample-2 > div').isVisible(), true);
  await feed.locator('#sample-2').getByRole('button', { name: 'Apply filter' }).click();
  checks.push('Reveal and collapse operate directly on posts in the X tab');
  const apply = async (page: Page, rules: string) => {
    await page.locator('#rules').fill(rules); await page.locator('#apply-rules').click();
    await page.waitForFunction(() => document.getElementById('rules-status')?.textContent === 'Applied');
  };
  const waitScore = async (post: string, percent: number) => {
    await feed.waitForFunction(({ post, percent }) => document.querySelector(`#${post} feed-analysis-controls`)?.shadowRoot?.textContent?.includes(`Turn down ${percent}%`), { post, percent });
  };
  const runningRules = 'Turn down running updates. Keep everything else, including ragebait and hype.';
  const calls = await worker.evaluate(() => (globalThis as any).calls);
  await popup.locator('#rules').fill(runningRules);
  assert.equal(await popup.locator('#rules-status').innerText(), 'Unapplied changes');
  assert.equal(await worker.evaluate(() => (globalThis as any).calls), calls);
  assert.equal(await feed.locator('article[data-fa-collapsed=true]').count(), 2);
  await apply(popup, runningRules); await waitScore('sample-5', 99); await waitScore('sample-2', 2);
  assert.equal(await feed.locator('article[data-fa-collapsed=true]').count(), 1);
  assert.equal(await feed.locator('article[data-fa-collapsed=true]').getAttribute('id'), 'sample-5');
  assert.equal((await worker.evaluate(() => chrome.storage.local.get('settings'))).settings.rules, runningRules);
  checks.push('Drafts make no calls; Apply persists free-form rules and changes the actual feed');
  await apply(popup, DEFAULT_RULES); await waitScore('sample-2', 98);
  await worker.evaluate(rules => { const w = globalThis as any; w.holdRules = rules; w.analysisAborted = false; w.analysisReady = new Promise<void>(resolve => { w.analysisStart = resolve; }); }, runningRules);
  await apply(popup, runningRules); await worker.evaluate(() => (globalThis as any).analysisReady);
  await worker.evaluate(() => { (globalThis as any).holdRules = ''; });
  await apply(popup, DEFAULT_RULES); await waitScore('sample-2', 98);
  assert.equal(await worker.evaluate(() => (globalThis as any).analysisAborted), true);
  checks.push('Applying newer rules aborts active scoring and prevents stale feed changes');
  const beforeStrength = await worker.evaluate(() => (globalThis as any).calls);
  await popup.locator('#strength').fill('40'); await popup.locator('#strength').dispatchEvent('input');
  await feed.waitForFunction(() => Number(document.querySelector<HTMLElement>('#sample-1')?.style.getPropertyValue('--fa-opacity')) > .98);
  assert.equal(await worker.evaluate(() => (globalThis as any).calls), beforeStrength);
  await popup.locator('#strength').fill('75'); await popup.locator('#strength').dispatchEvent('input');
  await popup.locator('#enabled').uncheck(); await feed.waitForFunction(() => document.querySelectorAll('article[data-fa-collapsed=true]').length === 0);
  await popup.locator('#enabled').check(); await feed.waitForFunction(() => document.querySelectorAll('article[data-fa-collapsed=true]').length === 2);
  checks.push('Fade strength reuses scores; pause restores the X feed');

  await popup.locator('#refresh-feed').click();
  await popup.locator('#story-section summary').click(); await popup.locator('#group-stories').click();
  await popup.waitForFunction(() => document.querySelectorAll('#story-list button').length === 5);
  await popup.locator('#story-list button').first().click();
  await feed.waitForFunction(() => document.querySelector('#sample-5')?.getAttribute('data-fa-collapsed') === 'true');
  assert.equal(await feed.locator('#sample-4').getAttribute('data-fa-collapsed'), 'false');
  await feed.evaluate(() => {
    const article = document.createElement('article'); article.dataset.testid = 'tweet'; article.id = 'unscored-post'; article.style.marginTop = '2000px';
    const body = document.createElement('div'); const p = document.createElement('p'); p.dataset.testid = 'tweetText'; p.textContent = 'A newly loaded post that has not been analyzed.';
    body.append(p); article.append(body); document.getElementById('feed')!.append(article);
  });
  await feed.waitForFunction(() => document.querySelector('#unscored-post')?.getAttribute('data-fa-collapsed') === 'false');
  assert.equal(await feed.locator('#unscored-post > div').isVisible(), true);
  assert.equal(await feed.locator('#unscored-post feed-analysis-controls').evaluate(e => e.shadowRoot?.textContent?.includes('Waiting')), true);
  await feed.evaluate(() => document.getElementById('unscored-post')!.remove());
  await worker.evaluate(() => { (globalThis as any).mode = 'unauthorized'; });
  await feed.evaluate(() => {
    const article = document.createElement('article'); article.dataset.testid = 'tweet'; article.id = 'failed-post';
    const body = document.createElement('div'); const p = document.createElement('p'); p.dataset.testid = 'tweetText'; p.textContent = 'A post with an unavailable score must remain readable.';
    body.append(p); article.append(body); document.getElementById('feed')!.prepend(article);
  });
  await feed.waitForFunction(() => document.querySelector('#failed-post feed-analysis-controls')?.shadowRoot?.textContent?.includes('rejected'));
  assert.equal(await feed.locator('#failed-post > div').isVisible(), true);
  assert.equal(await feed.locator('#failed-post').getAttribute('data-fa-collapsed'), 'false');
  await feed.screenshot({ path: resolve(root, 'artifacts/extension-story-error.png'), fullPage: true, animations: 'disabled' });
  await popup.locator('#clear-group').click();
  await feed.waitForFunction(() => document.querySelector('#sample-5')?.getAttribute('data-fa-collapsed') === 'false');
  assert.equal(await feed.locator('#failed-post > div').isVisible(), true);
  await feed.evaluate(() => document.getElementById('failed-post')!.remove());
  await worker.evaluate(() => { (globalThis as any).mode = 'fixture'; });
  checks.push('Selecting and clearing story focus keeps waiting and failed posts readable');
  await popup.locator('#topics button').filter({ hasText: 'Everyday life' }).click();
  await feed.waitForFunction(() => document.querySelector('#sample-1')?.getAttribute('data-fa-collapsed') === 'true');
  await popup.locator('#topics button').filter({ hasText: 'All posts' }).click();
  await feed.waitForFunction(() => document.querySelector('#sample-1')?.getAttribute('data-fa-collapsed') === 'false');
  await popup.locator('#story-section summary').click();
  checks.push('Topic and story groups focus real loaded posts in X, with clear-filter recovery');

  const options = await context.newPage(); await options.setViewportSize({ width: 900, height: 1050 });
  await options.goto(`chrome-extension://${id}/settings.html`); await options.waitForFunction(() => document.getElementById('connection')?.textContent === 'Connected');
  assert.equal(await options.locator('#posts, #analyze, #post-text, #open-lab').count(), 0);
  await options.locator('#rules').fill('My unfinished draft.');
  await apply(popup, runningRules); await waitScore('sample-5', 99);
  assert.equal(await options.locator('#rules').inputValue(), 'My unfinished draft.');
  assert.equal(await options.locator('#applied-rules-text').textContent(), runningRules);
  await apply(popup, DEFAULT_RULES); await waitScore('sample-2', 98);
  await options.locator('#rules').fill(DEFAULT_RULES);
  await options.screenshot({ path: resolve(root, 'artifacts/extension-settings.png'), fullPage: true, animations: 'disabled' });
  await options.setViewportSize({ width: 390, height: 844 });
  assert.equal(await options.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await options.screenshot({ path: resolve(root, 'artifacts/extension-settings-narrow.png'), fullPage: true, animations: 'disabled' });
  checks.push('Chrome settings contains only real controls and preserves drafts across windows');
  await options.locator('#provider').selectOption('cloudflare'); await options.locator('#account-id').fill('a'.repeat(32)); await options.locator('#api-key').fill('fixture-cloudflare-key');
  await options.locator('#key-form button').click(); await options.waitForFunction(() => document.getElementById('key-status')?.textContent === 'Connected to Cloudflare.');
  await waitScore('sample-2', 98);
  await options.locator('#provider').selectOption('typesafe'); await options.locator('#key-form button').click();
  await options.waitForFunction(() => document.getElementById('key-status')?.textContent === 'Connected to TypeSafe.'); await waitScore('sample-2', 98);
  checks.push('Provider switching still works with keys isolated and no local proxy');
  await popup.locator('#rules').fill(''); assert.equal(await popup.locator('#apply-rules').isDisabled(), true);
  await popup.locator('#rules').fill(DEFAULT_RULES);
  await popup.evaluate(() => { const w = globalThis as any; w.originalSendMessage = chrome.runtime.sendMessage; (chrome.runtime as any).sendMessage = (message: any) => message.type === 'applyRules' ? Promise.resolve({ ok: false, error: { message: 'Could not save rules. Please retry.' } }) : w.originalSendMessage(message); });
  await popup.locator('#rules').fill('Keep this draft if saving fails.'); await popup.locator('#apply-rules').click();
  await popup.waitForFunction(() => document.getElementById('rules-feedback')?.textContent === 'Could not save rules. Please retry.');
  assert.equal(await popup.locator('#applied-rules-text').textContent(), DEFAULT_RULES);
  assert.equal(await popup.locator('#rules').inputValue(), 'Keep this draft if saving fails.');
  const feedback = (await popup.locator('#rules-feedback').boundingBox())!; assert.ok(feedback.y + feedback.height < 600);
  await popup.screenshot({ path: resolve(root, 'artifacts/extension-popup-error.png'), fullPage: true, animations: 'disabled' });
  await popup.evaluate(() => { (chrome.runtime as any).sendMessage = (globalThis as any).originalSendMessage; });
  await popup.locator('#rules').fill(DEFAULT_RULES);
  checks.push('Blank drafts are blocked and save errors preserve both draft and applied rules');
  await popup.locator('#refresh-feed').click();
  await popup.screenshot({ path: resolve(root, 'artifacts/extension-popup.png'), fullPage: true, animations: 'disabled' });
  assert.equal(await popup.evaluate(() => document.documentElement.scrollWidth), 360);
  const started = await worker.evaluate(() => (globalThis as any).calls);
  await feed.evaluate(() => history.pushState({}, '', '/messages/123'));
  await feed.waitForFunction(() => document.querySelectorAll('feed-analysis-controls').length === 0);
  assert.equal(await worker.evaluate(() => (globalThis as any).calls), started);
  checks.push('Messages navigation removes overlays and sends no text');
  assert.equal(localRequests, 0);
  checks.push('Every extension flow succeeds with localhost blocked');
  return popup;
}
